In [85]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [86]:
df=pd.read_csv(r'C:\Users\mayur\OneDrive\Desktop\data science training\panda\data\used_bike.csv')

In [87]:
df

      Unnamed: 0  city  owner  brand     price  kms_driven  age  power
0              0   1.0      1      1   35000.0     17654.0  3.0  110.0
1              1   2.0      1      2  119900.0     11000.0  4.0  350.0
2              2   2.0      1      3  600000.0       110.0  8.0  675.0
3              3   3.0      1      1   65000.0     16329.0  4.0  180.0
4              4   3.0      1      4   80000.0     10000.0  3.0  150.0
...          ...   ...    ...    ...       ...         ...  ...    ...
7309        9362   2.0      1      6   25000.0     48587.0  8.0  150.0
7310        9369   3.0      1      7   35000.0     60000.0  9.0  220.0
7311        9370   NaN      1     15  450000.0      3430.0  4.0  750.0
7312        9371   8.0      1      7  139000.0     21300.0  4.0  400.0
7313        9372   8.0      1      7   80000.0      7127.0  5.0  220.0

[7314 rows x 8 columns]

In [88]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [89]:
df.duplicated().sum()

np.int64(0)

In [90]:
df.isnull().sum()

city          3153
owner            0
brand            0
price            0
kms_driven       0
age              0
power            0
dtype: int64

In [91]:
df.drop('city', axis =1 , inplace = True )

In [92]:
x=df.drop('price',axis=1)
y=df[['price']]

In [93]:
x

      owner  brand  kms_driven  age  power
0         1      1     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1      3       110.0  8.0  675.0
3         1      1     16329.0  4.0  180.0
4         1      4     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
7309      1      6     48587.0  8.0  150.0
7310      1      7     60000.0  9.0  220.0
7311      1     15      3430.0  4.0  750.0
7312      1      7     21300.0  4.0  400.0
7313      1      7      7127.0  5.0  220.0

[7314 rows x 5 columns]

In [94]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7309   25000.0
7310   35000.0
7311  450000.0
7312  139000.0
7313   80000.0

[7314 rows x 1 columns]

In [95]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [96]:
x_train

      owner  brand  kms_driven  age  power
5071      1      2      5222.0  5.0  350.0
565       1      1      2980.0  6.0  160.0
4500      1      6     19000.0  5.0  100.0
4030      1      8      7900.0  6.0  150.0
640       1      6     28329.0  6.0  110.0
...     ...    ...         ...  ...    ...
5191      1      4     14400.0  4.0  150.0
5226      1      5     15768.0  6.0  125.0
5390      1      2      9500.0  3.0  410.0
860       1      4     14836.0  8.0  150.0
7270      2      5     14000.0  4.0  250.0

[5851 rows x 5 columns]

In [97]:
x_test

      owner  brand  kms_driven   age  power
5832      1      5     22500.0   4.0  125.0
1562      1      6      6600.0   2.0  200.0
7181      1      6      2584.0  11.0  100.0
2825      1      7     44000.0  13.0  180.0
4890      1     10     27874.0   4.0  390.0
...     ...    ...         ...   ...    ...
57        1     12      2500.0   2.0  900.0
6192      1      4     42386.0   6.0  150.0
4411      1      7     22000.0   5.0  150.0
527       1     14      2881.0   7.0  250.0
3305      1      8     23833.0   4.0  150.0

[1463 rows x 5 columns]

In [98]:
y_train

         price
5071  118000.0
565    36000.0
4500   33100.0
4030   70000.0
640    32000.0
...        ...
5191   75000.0
5226   26000.0
5390  170000.0
860    40000.0
7270  120000.0

[5851 rows x 1 columns]

In [99]:
y_test

         price
5832   48000.0
1562   88000.0
7181   20000.0
2825   18158.0
4890  180000.0
...        ...
57    935000.0
6192   64466.0
4411   65000.0
527   140000.0
3305   54500.0

[1463 rows x 1 columns]

In [100]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5851, 5), (1463, 5), (5851, 1), (1463, 1))

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr.fit(x_train,y_train)
import joblib
joblib.dump(rfr,"rfr_model.lb")2

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

['rfr_model.lb']

In [102]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [103]:
pred=lr.predict(x_test)

In [104]:
y_test

         price
5832   48000.0
1562   88000.0
7181   20000.0
2825   18158.0
4890  180000.0
...        ...
57    935000.0
6192   64466.0
4411   65000.0
527   140000.0
3305   54500.0

[1463 rows x 1 columns]

In [105]:
print("test score:-",lr.score(x_test,y_test))
print("training score:-",lr.score(x_train,y_train))

test score:- 0.7695278321699431
training score:- 0.7055696989224549

In [106]:
# svm

from sklearn .svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [107]:
print("svr",sv.score(x_test,y_test))
print("svr",sv.score(x_train,y_train))

svr -0.061520056314581684
svr -0.060858927241484784

In [108]:
from sklearn.datasets  import load_breast_cancer
import joblib
x,y=load_breast_cancer(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)
print("svc training",sv.score(x_train,y_train))
print("svc testing",sv.score(x_test,y_test))
joblib.dump(sv,"sv_load.lb")

svc training 0.9142857142857143
svc testing 0.9473684210526315

['sv_load.lb']

In [109]:
import joblib
joblib.dump(sv,"sv_load.lb")

['sv_load.lb']

In [110]:
model=joblib.load('sv_load.lb')

In [111]:
model.predict(x_test)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [112]:
sv.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [113]:
from sklearn.datasets  import load_diabetes
x,y=load_diabetes(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)
print("svr training",sv.score(x_train,y_train))
print("svr testing",sv.score(x_test,y_test))

svr training 0.1668037716306
svr testing 0.18211365770500287

In [114]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [115]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [118]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn .datasets import load_diabetes
x,y=load_diabetes(return_X_y=True)
KNeighborsRegressor().fit(x,y)

KNeighborsRegressor()

In [119]:
from sklearn .datasets import load_breast_cancer
x,y=load_breast_cancer(return_X_y=True)
KNeighborsClassifier().fit(x,y)

KNeighborsClassifier()

In [120]:
kn=KNeighborsClassifier()
kn.fit(x_train,y_train)
print("knc training",kn.score(x_train,y_train))
print("knc testing",kn.score(x_test,y_test))

knc training 0.19263456090651557
knc testing 0.0

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\neighbors\_base.py:501: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  check_classification_targets(y)